module.exports = [
	'PRESENT',
	'FUTUR',
	'IMPARFAIT',
	'PASSE_SIMPLE',
	'CONDITIONNEL_PRESENT',
	'IMPERATIF_PRESENT',
	'SUBJONCTIF_PRESENT',
	'SUBJONCTIF_IMPARFAIT',
	'PASSE_COMPOSE',
	'PLUS_QUE_PARFAIT'
];